### ISSUE TITLE
Nothing logging when running the script

### ISSUE THREAD

**Issue by AJackTi** [666pulse/raydium-lp-tracker#1]
When I ran this script, I didn't log anything. Could you give me some suggestions to run it correctly? Thanks

`❯ ts-node app.ts
Monitoring logs for program:  675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8`
...

**Comment by liushooter** [comment]
> ![](https://github.com/666pulse/raydium-lp-tracker/assets/1235106/9f29e95b-7d43-4f19-9d9b-9d706ca710ac)

You'll need the following config：

```js
const HTTP_URL = ""
const WSS_URL = ""
```
And wait a little time or a few minutes

**Comment by AJackTi** [comment]
I already set 2 constants from the alchemy provider. But after more than 10 minutes, It's not print anything. I don't know why. Please help me.

**Comment by liushooter** [comment]
you can try quiknode rpc. alchemy not support  some solana rpc method. @AJackTi

**Comment by AJackTi** [comment]
I used quicknode rpc, so It's ok. It's always print `Error fetching transaction:`, and don't print the table like the above image. Let's me monitor further.

I had a pull request to refactor code and fix wrong code. Let's help me to review it and merge if It's ok: [link](https://github.com/666pulse/raydium-lp-tracker/pull/2)
